http {
   # Настройка upstream для балансировки нагрузки
   upstream backend_servers {
       server backend1.example.com;
       server backend2.example.com;
       server backend3.example.com;
   }

   # Настройка лимитов запросов
   # не более 10 запросов в минуту
   limit_req_zone $binary_remote_addr zone=req_zone_limit:10m rate=10r/m;

   server {
       listen 80;

       location / {
           proxy_pass http://backend_servers;

           # включает ограничение скорости 
           limit_req zone=req_zone_limit;

           # при превышении лимита запросов отдавать HTTP-ошибку с кодом 429
           limit_req_status 429;
       }

   }
}
 